from dataclasses import dataclass
from typing import List

@dataclass
class Airport:
    iata: str
    name: str
    city: str
    country: str
    flag: str
    lat: float = 0.0
    lon: float = 0.0

# COMMON DESTINATIONS SERVED BY RYANAIR FROM BOTH MILAN AND RIGA
CANDIDATE_DESTINATIONS = [
    Airport("BGY", "Milan Bergamo", "Milan", "Italy", "🇮🇹", 45.67, 9.70),
    Airport("MXP", "Milan Malpensa", "Milan", "Italy", "🇮🇹", 45.63, 8.72),
    Airport("LIN", "Milan Linate", "Milan", "Italy", "🇮🇹", 45.45, 9.28),
    Airport("CRL", "Brussels Charleroi", "Brussels", "Belgium", "🇧🇪", 50.46, 4.45),
    Airport("BER", "Berlin Brandenburg", "Berlin", "Germany", "🇩🇪", 52.37, 13.50),
    Airport("VIE", "Vienna International", "Vienna", "Austria", "🇦🇹", 48.11, 16.56),
    Airport("BUD", "Budapest Ferenc Liszt", "Budapest", "Hungary", "🇭🇺", 47.43, 19.26),
    Airport("PRG", "Prague Václav Havel", "Prague", "Czech Republic", "🇨🇿", 50.10, 14.26),
    Airport("WAW", "Warsaw Chopin", "Warsaw", "Poland", "🇵🇱", 52.17, 20.97),
    Airport("CPH", "Copenhagen", "Copenhagen", "Denmark", "🇩🇰", 55.62, 12.65),
    Airport("BCN", "Barcelona–El Prat", "Barcelona", "Spain", "🇪🇸", 41.30, 2.08),
    Airport("MAD", "Madrid–Barajas", "Madrid", "Spain", "🇪🇸", 40.49, -3.57),
    Airport("FRA", "Frankfurt", "Frankfurt", "Germany", "🇩🇪", 50.03, 8.57),
    Airport("BVA", "Paris Beauvais", "Paris", "France", "🇫🇷", 49.45, 2.11),
    Airport("LIS", "Lisbon", "Lisbon", "Portugal", "🇵🇹", 38.77, -9.14),
    Airport("OPO", "Porto", "Porto", "Portugal", "🇵🇹", 41.24, -8.68),
    Airport("AGP", "Málaga", "Málaga", "Spain", "🇪🇸", 36.67, -4.50),
    Airport("ATH", "Athens International", "Athens", "Greece", "🇬🇷", 37.94, 23.94),
    Airport("RIX", "Riga International", "Riga", "Latvia", "🇱🇻", 56.92, 23.97),
    Airport("TSF", "Treviso", "Venice", "Italy", "🇮🇹", 45.65, 12.20),
    Airport("VLC", "Valencia", "Valencia", "Spain", "🇪🇸", 39.49, -0.48),
    Airport("PMI", "Palma de Mallorca", "Palma", "Spain", "🇪🇸", 39.55, 2.73),
    Airport("VCE", "Venice Marco Polo", "Venice", "Italy", "🇮🇹", 45.51, 12.35),
    Airport("HEL", "Helsinki", "Helsinki", "Finland", "🇫🇮", 60.31, 24.96),
    Airport("ARN", "Stockholm Arlanda", "Stockholm", "Sweden", "🇸🇪", 59.65, 17.91),
    Airport("OSL", "Oslo Gardermoen", "Oslo", "Norway", "🇳🇴", 60.19, 11.10),
    Airport("MUC", "Munich", "Munich", "Germany", "🇩🇪", 48.35, 11.78),
    Airport("ZRH", "Zurich", "Zurich", "Switzerland", "🇨🇭", 47.45, 8.55),
    Airport("AMS", "Amsterdam Schiphol", "Amsterdam", "Netherlands", "🇳🇱", 52.31, 4.76),
    Airport("BRU", "Brussels", "Brussels", "Belgium", "🇧🇪", 50.90, 4.48),
    Airport("CDG", "Paris Charles de Gaulle", "Paris", "France", "🇫🇷", 49.01, 2.55),
    Airport("NCE", "Nice Côte d'Azur", "Nice", "France", "🇫🇷", 43.66, 7.21),
    Airport("MRS", "Marseille Provence", "Marseille", "France", "🇫🇷", 43.43, 5.21),
    Airport("LYS", "Lyon–Saint-Exupéry", "Lyon", "France", "🇫🇷", 45.72, 5.08),
    Airport("HAM", "Hamburg", "Hamburg", "Germany", "🇩🇪", 53.63, 9.98),
    Airport("DUS", "Düsseldorf", "Düsseldorf", "Germany", "🇩🇪", 51.28, 6.76),
    Airport("STR", "Stuttgart", "Stuttgart", "Germany", "🇩🇪", 48.69, 9.22),
    Airport("NAP", "Naples International", "Naples", "Italy", "🇮🇹", 40.88, 14.29),
    Airport("CTA", "Catania–Fontanarossa", "Catania", "Italy", "🇮🇹", 37.47, 15.06),
    Airport("PMO", "Palermo", "Palermo", "Italy", "🇮🇹", 38.18, 13.10),
    Airport("PSA", "Pisa International", "Pisa", "Italy", "🇮🇹", 43.68, 10.40),
    Airport("BLQ", "Bologna Guglielmo Marconi", "Bologna", "Italy", "🇮🇹", 44.53, 11.28),
    Airport("VNO", "Vilnius International", "Vilnius", "Lithuania", "🇱🇹", 54.64, 25.28),
    Airport("TLL", "Tallinn", "Tallinn", "Estonia", "🇪🇪", 59.41, 24.83),
    Airport("POZ", "Poznań–Ławica", "Poznań", "Poland", "🇵🇱", 52.42, 16.82),
    Airport("WRO", "Wrocław Copernicus", "Wrocław", "Poland", "🇵🇱", 51.10, 16.88),
    Airport("KRK", "Kraków John Paul II", "Kraków", "Poland", "🇵🇱", 50.08, 19.78),
    Airport("SKG", "Thessaloniki", "Thessaloniki", "Greece", "🇬🇷", 40.52, 22.97),
    Airport("HER", "Heraklion International", "Heraklion", "Greece", "🇬🇷", 35.34, 25.18),
    Airport("CFU", "Corfu International", "Corfu", "Greece", "🇬🇷", 39.61, 19.91),
    Airport("LPA", "Gran Canaria", "Gran Canaria", "Spain", "🇪🇸", 27.93, -15.38),
    Airport("TFS", "Tenerife South", "Tenerife", "Spain", "🇪🇸", 28.04, -16.57),
    Airport("SVQ", "Seville", "Seville", "Spain", "🇪🇸", 37.42, -5.89),
    Airport("ALC", "Alicante–Elche", "Alicante", "Spain", "🇪🇸", 38.28, -0.56),
    Airport("BIO", "Bilbao", "Bilbao", "Spain", "🇪🇸", 43.30, -2.91),
    Airport("FCO", "Rome Fiumicino", "Rome", "Italy", "🇮🇹", 41.80, 12.23),
    Airport("CIA", "Rome Ciampino", "Rome", "Italy", "🇮🇹", 41.80, 12.59),
    Airport("MLA", "Malta", "Malta", "Malta", "🇲🇹", 35.85, 14.47),
    Airport("GVA", "Geneva", "Geneva", "Switzerland", "🇨🇭", 46.23, 6.10),
    Airport("LUX", "Luxembourg", "Luxembourg", "Luxembourg", "🇱🇺", 49.62, 6.20),
    Airport("BTS", "Bratislava", "Bratislava", "Slovakia", "🇸🇰", 48.17, 17.21),
    Airport("LJU", "Ljubljana", "Ljubljana", "Slovenia", "🇸🇮", 46.22, 14.45),
    Airport("IBZ", "Ibiza", "Ibiza", "Spain", "🇪🇸", 38.87, 1.37),
    Airport("MAH", "Menorca", "Menorca", "Spain", "🇪🇸", 39.86, 4.21),
    Airport("RHO", "Rhodes", "Rhodes", "Greece", "🇬🇷", 36.40, 28.08),
    Airport("JTR", "Santorini", "Santorini", "Greece", "🇬🇷", 36.40, 25.47),
    Airport("JMK", "Mykonos", "Mykonos", "Greece", "🇬🇷", 37.43, 25.34),
    Airport("ZAD", "Zadar", "Zadar", "Croatia", "🇭🇷", 44.10, 15.34),
    Airport("SPU", "Split", "Split", "Croatia", "🇭🇷", 43.53, 16.29),
    Airport("DBV", "Dubrovnik", "Dubrovnik", "Croatia", "🇭🇷", 42.56, 18.26),
    # FINAL MASSIVE SCHENGEN EXPANSION
    Airport("TRN", "Turin", "Turin", "Italy", "🇮🇹", 45.20, 7.65),
    Airport("GOA", "Genoa", "Genoa", "Italy", "🇮🇹", 44.41, 8.85),
    Airport("VRN", "Verona", "Verona", "Italy", "🇮🇹", 45.40, 10.89),
    Airport("TRS", "Trieste", "Trieste", "Italy", "🇮🇹", 45.83, 13.47),
    Airport("BDS", "Brindisi", "Brindisi", "Italy", "🇮🇹", 40.66, 17.95),
    Airport("SUF", "Lamezia Terme", "Lamezia", "Italy", "🇮🇹", 38.91, 16.24),
    Airport("CAG", "Cagliari", "Cagliari", "Italy", "🇮🇹", 39.25, 9.06),
    Airport("OLB", "Olbia Costa Smeralda", "Olbia", "Italy", "🇮🇹", 40.90, 9.52),
    Airport("AHO", "Alghero", "Alghero", "Italy", "🇮🇹", 40.63, 8.29),
    Airport("PEG", "Perugia", "Perugia", "Italy", "🇮🇹", 43.09, 12.51),
    Airport("AOI", "Ancona", "Ancona", "Italy", "🇮🇹", 43.62, 13.36),
    Airport("TLS", "Toulouse–Blagnac", "Toulouse", "France", "🇫🇷", 43.63, 1.37),
    Airport("BOD", "Bordeaux–Mérignac", "Bordeaux", "France", "🇫🇷", 44.83, -0.72),
    Airport("NTE", "Nantes Atlantique", "Nantes", "France", "🇫🇷", 47.16, -1.61),
    Airport("MPL", "Montpellier–Méditerranée", "Montpellier", "France", "🇫🇷", 43.58, 3.96),
    Airport("BIA", "Bastia – Poretta", "Bastia", "France", "🇫🇷", 42.55, 9.49),
    Airport("SCQ", "Santiago de Compostela", "Santiago", "Spain", "🇪🇸", 42.90, -8.42),
    Airport("VGO", "Vigo–Peinador", "Vigo", "Spain", "🇪🇸", 42.23, -8.63),
    Airport("OVD", "Asturias", "Oviedo", "Spain", "🇪🇸", 43.56, -6.03),
    Airport("SDR", "Santander", "Santander", "Spain", "🇪🇸", 43.43, -3.82),
    Airport("VIT", "Vitoria", "Vitoria", "Spain", "🇪🇸", 42.88, -2.72),
    Airport("GRO", "Girona–Costa Brava", "Girona", "Spain", "🇪🇸", 41.90, 2.76),
    Airport("REU", "Reus", "Reus", "Spain", "🇪🇸", 41.15, 1.17),
    Airport("RMU", "Región de Murcia", "Murcia", "Spain", "🇪🇸", 37.80, -1.12),
    Airport("LEI", "Almería", "Almería", "Spain", "🇪🇸", 36.85, -2.37),
    Airport("XRY", "Jerez", "Jerez", "Spain", "🇪🇸", 36.74, -6.06),
    Airport("ACE", "Lanzarote", "Lanzarote", "Spain", "🇪🇸", 28.95, -13.61),
    Airport("FUE", "Fuerteventura", "Fuerteventura", "Spain", "🇪🇸", 28.45, -13.87),
    Airport("SPC", "La Palma", "La Palma", "Spain", "🇪🇸", 28.63, -17.76),
    Airport("CGN", "Cologne Bonn", "Cologne", "Germany", "🇩🇪", 50.87, 7.14),
    Airport("FKB", "Karlsruhe/Baden-Baden", "Karlsruhe", "Germany", "🇩🇪", 48.78, 8.08),
    Airport("BRE", "Bremen", "Bremen", "Germany", "🇩🇪", 53.05, 8.79),
    Airport("HAJ", "Hanover", "Hanover", "Germany", "🇩🇪", 52.46, 9.68),
    Airport("LEJ", "Leipzig/Halle", "Leipzig", "Germany", "🇩🇪", 51.42, 12.24),
    Airport("NUE", "Nuremberg", "Nuremberg", "Germany", "🇩🇪", 49.50, 11.08),
    Airport("GDN", "Gdańsk Lech Wałęsa", "Gdańsk", "Poland", "🇵🇱", 54.38, 18.47),
    Airport("KTW", "Katowice", "Katowice", "Poland", "🇵🇱", 50.47, 19.08),
    Airport("WMI", "Warsaw Modlin", "Warsaw", "Poland", "🇵🇱", 52.45, 20.65),
    Airport("RZE", "Rzeszów–Jasionka", "Rzeszów", "Poland", "🇵🇱", 50.11, 22.02),
    Airport("SZZ", "Solidarity Szczecin–Goleniów", "Szczecin", "Poland", "🇵🇱", 53.58, 14.90),
    Airport("BZG", "Bydgoszcz Ignacy Jan Paderewski", "Bydgoszcz", "Poland", "🇵🇱", 53.10, 17.98),
    Airport("LUZ", "Lublin", "Lublin", "Poland", "🇵🇱", 51.24, 22.71),
    Airport("GOT", "Göteborg Landvetter", "Gothenburg", "Sweden", "🇸🇪", 57.66, 12.29),
    Airport("BLL", "Billund", "Billund", "Denmark", "🇩🇰", 55.74, 9.15),
    Airport("AAL", "Aalborg", "Aalborg", "Denmark", "🇩🇰", 57.09, 9.85),
    Airport("TMP", "Tampere–Pirkkala", "Tampere", "Finland", "🇫🇮", 61.41, 23.60),
    Airport("TKU", "Turku", "Turku", "Finland", "🇫🇮", 60.51, 22.26),
    Airport("EIN", "Eindhoven", "Eindhoven", "Netherlands", "🇳🇱", 51.46, 5.37),
    Airport("MST", "Maastricht Aachen", "Maastricht", "Netherlands", "🇳🇱", 50.91, 5.77),
    Airport("RTM", "Rotterdam The Hague", "Rotterdam", "Netherlands", "🇳🇱", 51.96, 4.44),
    Airport("BSL", "EuroAirport Basel Mulhouse Freiburg", "Basel", "Switzerland", "🇨🇭", 47.59, 7.53),
]

def get_destinations(exclude_iatas: List[str]) -> List[Airport]:
    # Ensure origins are always excluded
    return [a for a in CANDIDATE_DESTINATIONS if a.iata not in exclude_iatas]

def load_europe_airports_from_ourairports():
    pass
